### PR TITLE
Add compatibility with Laravel Nova 2.0

### LINKED ISSUE #2: Declaration of BooleanDatetime::nullable
hi,
after updating to nova 2.0 , I got this error : 

`Declaration of PragmaRX\BooleanDatetime\BooleanDatetime::nullable() should be compatible with Laravel\Nova\Fields\Field::nullable($nullable = true, $values = NULL)`

my Code is : 

```
use PragmaRX\BooleanDatetime\BooleanDatetime;

BooleanDatetime::make('Is Active?', 'email_verified_at')->nullable()
```
even if I remove the `nullable` .

### PR DESCRIPTION
**Pull request by tekreme73**
Fix #2

### CODE REVIEW

**Comment by antonioribeiro** [comment]
Will not work for people using PHP 7.1 anymore, why?

**Comment by tekreme73** [comment]
You are right, I don't know why I upgrade this version. That's the one we are using in our project but Laravel Nova 2.0 requires PHP 7.1. So we can leave this version for this field.

**Comment by antonioribeiro** [comment]
Cool! Thank you

**Comment by atmonshi** [comment]
thanks a lot for the fix.

new release soon ? 🤞 :)

**Comment by mydnic** [comment]
@antonioribeiro can you tag a new release ? :) thanks !

**Comment by depsimon** [comment]
@antonioribeiro Thanks for merging, could you tag a new release please?

**Pull request merged**
